### ISSUE TITLE
Homebrew formulae

### ISSUE THREAD

**Issue by marlun** [andmarti1424/sc-im#52]
It would be really nice if a homebrew formulae was created making it easy to install/uninstall sc-im on a mac.

**Comment by andmarti1424** [comment]
I do not have a mac. I believe it would best be added by someone who has one.

**Comment by andmarti1424** [comment]
May be write a wiki as well?

**Comment by willhoag** [comment]
Would love this as a homebrew formulae. Don't know Ruby, so here is my +1

**Comment by cody-code-wy** [comment]
I think I will try to make this happen.

**Comment by andmarti1424** [comment]
That would be great!

**Comment by andmarti1424** [comment]
Hello @cody-code-wy! Could you have any progress in this?

**Comment by gwerbin** [comment]
Funnily enough I was just working on this. However I can't get v0.3.0 to build on my Mac. This is the error I receive:

```
$ make CC=clang LDFLAGS=-L/usr/local/opt/ncurses/lib CFLAGS=-I/usr/local/opt/ncurses/include PKG_CONFIG_PATH=/usr/local/opt/ncurses/lib/pkgconfig

gcc -I/usr/local/Cellar/ncurses/6.0_2/include -I/usr/local/Cellar/ncurses/6.0_2/include -I/usr/local/Cellar/ncurses/6.0_2/include/ncursesw  -c -o help.o help.c
help.c:29:42: error: use of undeclared identifier 'HELP_PATH'
    sprintf(helpfile_path, "%s/%s_help", HELP_PATH, SNAME);
                                         ^
help.c:29:53: error: use of undeclared identifier 'SNAME'
    sprintf(helpfile_path, "%s/%s_help", HELP_PATH, SNAME);
```

**Comment by andmarti1424** [comment]
Seems that you are not passing the different flags, such as HELP_PATH, to the compiler.
Are you using the Makefile that is inside src folder?

**Comment by rjungemann** [comment]
First off, thank you for sc-im, it is a really great program.

I was not able to make a formula which builds sc-im on the fly, but I made a formula that installs a pre-built version of sc-im. If I get more time, I will try and make a formula which applies patches dynamically, so sc-im can be built on-the-fly.

https://gist.github.com/rjungemann/330b5f7230d5f33cfd5f970089fc0383

There are instructions at the top of the formula of how I built it.

Some notes:

* Despite what is noted in https://github.com/andmarti1424/sc-im/issues/107, I cannot get colors working in v0.4.0. So I built with v0.3.0. I tried a clean install of everything and I also tried using the dupes version of ncurses.
* For some reason, I had to go and literally modify `src/macros.h` in order to get backspace working. It was not enough to set the `MACOSX` environment variable. This may be user error.
* This recipe currently has a hardcoded prefix of `/usr/local`. This can be fixed by dynamically applying a patch.
* Help should work. This took me a little bit of time to figure out.

If I get some more time, I will try and make a version of the formula with all of these patches applied automatically and with the prefix not-hardcoded. Or, I hope maybe someone can build on this and make a formula that can build sc-im on the fly.

**Comment by andmarti1424** [comment]
Thanks for your work. Hope it would help to others. About the color issue.. That is very weird. Don't know what could cause this..

**Comment by andmarti1424** [comment]
Does colors work OK in your v0.3.0 build?

**Comment by rjungemann** [comment]
@andmarti1424 Yeah colors works okay in my v0.3.0 build! I'll have some time to take a deeper look later this week, to see if I can get sc-im to build inside of a Homebrew recipe (Homebrew adds a ton of environment variables and it makes it hard to figure out what is going on), and if I can get colors working in v0.4.0.

**Comment by andmarti1424** [comment]
Could you adapt v0.3.0 makefile to v0.4.0v source, and try building it? I believe the colors problem, is a linking issue to ncursesw library..

**Comment by andmarti1424** [comment]
@rjungemann, could you test colors with v0.5?? or better.. taking the latest commit in freeze branch?

**Comment by yokattana** [comment]
I expect to have a good formula ready in a few days. It's not hard but I want it to be a good formula (and I have work to worry about too, ha).

**Comment by andmarti1424** [comment]
That would be great!

**Comment by yokattana** [comment]
I still want to do this but other things have gotten in my way. If anyone feels inspired to pick it up, feel free.

**Comment by nickolasburr** [comment]
https://github.com/nickolasburr/homebrew-sc-im

**Comment by andmarti1424** [comment]
Thanks @nichkolasburr. Do I need to make a change to support you formulae?

**Comment by nickolasburr** [comment]
@andmarti1424 No, I've configured it to work with the current setup. For new releases, I'll need to update the release version in the formula, so feel free to send a PR or just notify me.

**Comment by andmarti1424** [comment]
Good. Ill update the wiki and close this issue. Thanks again.

**Comment by sedm0784** [comment]
Not sure if I'm being an idiot, but I can't find any mention of the new formula in either the README or the wiki?

**Comment by andmarti1424** [comment]
https://github.com/andmarti1424/sc-im/wiki/Homebrew-formulae

**Comment by sedm0784** [comment]
...and there it is in the list of pages! So either I *was* being an idiot, or I was somehow looking at a cached version of the wiki. Either way, apologies for wasting your time.

**Comment by andmarti1424** [comment]
No problem.

**Comment by nickolasburr** [comment]
Hey @andmarti1424, it looks like a formula for sc-im was merged into homebrew-core about a month ago (see [here](https://github.com/Homebrew/homebrew-core/commit/fa3415c1e692cd646916c9eaf0db44042d2af1bb) and [here](https://github.com/Homebrew/homebrew-core/pull/14067)). This is news to me, as they didn't bother to leave a comment. I can send over a PR to update the README in the next day or so if you're not able to get to it before then.

**Comment by andmarti1424** [comment]
Hello @nickolasburr. Is the formula merged to homebrew-core, your formula?

**Comment by nickolasburr** [comment]
@andmarti1424 No, it was created and submitted by another user. The original PR can be found [here](https://github.com/Homebrew/homebrew-core/pull/12260).

**Comment by andmarti1424** [comment]
Why dont just keep yours?

**Comment by nickolasburr** [comment]
@andmarti1424 We definitely can, but since there exists a formula with a matching name in homebrew-core, it's likely going to cause confusion. For example, regardless of whether you `brew tap nickolasburr/pfa` or not, when you search for the formula by name (i.e. `brew search sc-im`) or perform a lookup of the formula information (i.e. `brew info sc-im`), you'll now get the homebrew-core version, not the tap version. You would _instead_ have to prepend the tap namespace to the formula (i.e. `brew info nickolasburr/pfa/sc-im`) to get the tap version. Such is the nature of Homebrew - when there are two or more matching formula names, homebrew-core formulae doesn't require a namespace, while tap formulae does.

With that said, it's completely at your discretion on how you'd like to proceed. I'm perfectly fine with keeping the tap formula intact and updating the README to reflect this change. On the other hand, if you'd prefer to use the homebrew-core formula, I can make the necessary updates to reflect that change, as well.

**Comment by andmarti1424** [comment]
May be update to include the homebrew-core, but leaving yours? We do not know if the other will be  kept updated.

**Comment by gwerbin** [comment]
@andmarti1424 @nickolasburr why not just take over maintenance of the Homebrew version? If you're already keeping tabs on releases (btw, THANK YOU for doing this), then there's no reason to update the separate tap when you could just as easily submit a PR to update the Homebrew version. The only way that would fail is if the Homebrew maintainer(s) get overloaded, or they disappear and the project starts dying, which seems unlikely any time soon.

**Comment by nickolasburr** [comment]
@gwerbin @andmarti1424 I think that's a solid plan, I was just hesitant to take ownership of a formula someone else might have been managing. I'll look to get the homebrew-core version updated and a PR sent in the near future. Thanks for the feedback.

**Comment by andmarti1424** [comment]
@nickolasburr, great then!
