### ISSUE TITLE
[BUG] sc-im doesn't build on Ubuntu 20.04

### ISSUE THREAD

**Issue by emk2203** [andmarti1424/sc-im#403]
On a stock Ubuntu 20.04 with dependencies according to wiki, `bison` and `build-essential` installed, the `make` process throws errors, starting with:

```
/usr/bin/ld: cmds.o: in function `doformat':
/home/emk2203/src/sc-im/src/cmds.c:684: undefined reference to `COLS'
```
followed by more undefined references to COLS, LINES and a lot of others.

**Comment by agentgoblin** [comment]
In tiu.c I found this comment:

` * if not working with ncurses, you should also have to define LINES and COLS macros in Xui.h as well. `

LINES and COLS is defined in ncurses.h. Be sure if libncurses*-dev package installed on the your PC.

**Comment by andmarti1424** [comment]
Be sure to link against ncurses

**Comment by andmarti1424** [comment]
Could you solve this?
